version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123!", "-Q", "SELECT 1", "-No"]
      interval: 10s
      timeout: 5s
      retries: 10

  userservice:
    build:
      context: .
      dockerfile: User_Service/Dockerfile
    container_name: userservice
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=UserDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;"
    ports:
      - "5001:8080"

  apigateway:
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    container_name: apigateway
    depends_on:
      - userservice
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:8080"

volumes:
  sql_data: